#
# Docker Compose 設定ファイル
# - Keycloak & mod_auth_openidc example -
#
version: '3'

# ボリューム設定(データ永続化)
volumes:

  # MySQL用ボリューム設定
  mysql_data:
      driver: local

# 各コンテナサービス設定
services:

  # LBコンテナ設定
  lb:
    container_name: kc-example-lb
    build:
      context: ./lb
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    depends_on:
      - rp
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./lb/certs:/etc/nginx/certs
    networks:
      default:
        aliases:
          - sso.example.com
          - app1.example.com
          - app2.example.com

  # RP(Apache+mod_auth_openidc)コンテナ設定
  rp:
    container_name: kc-example-rp
    build:
      context: ./reverse_proxy
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    ports:
      - 81:80
    environment:
      VIRTUAL_HOST: "*.example.com"
      CERT_NAME: example
    networks:
       - default

  # DB(MySQL)コンテナ設定
  db:
    container_name: kc-example-db
    build:
      context: ./mysql
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloakdb
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - default

  # OP(Keycloak)コンテナ設定
  op:
    container_name: kc-example-op
    build:
      context: ./keycloak
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db
      DB_DATABASE: keycloakdb
      DB_USER: keycloak
      DB_PASSWORD: password
      JDBC_PARAMS: "useSSL=false"
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
    networks:
      - default
# No mac
#    extra_hosts:
#      - host.docker.internal:172.18.0.1

  # App1コンテナ設定
  app1:
    container_name: kc-example-app1
    build:
      context: ./echo
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    ports:
      - 8081:80
    networks:
      - default

  # App2コンテナ設定
  app2:
    container_name: kc-example-app2
    build:
      context: ./echo
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    ports:
      - 8082:80
    networks:
      - default

# SMTPコンテナ設定
  smtp:
    container_name: kc-example-smtp
    build:
      context: ./smtp
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    ports:
      - 5025:5025
      - 5080:5080
    environment:
      VIRTUAL_HOST: "smtp.example.com"
      VIRTUAL_PORT: "5080"
    networks:
      - default

